server:
  port: 7001
  servlet:
    context-path: /jegykassza

spring:
  application:
    name: idm-adapter-backend
  profiles:
    active: local-dev-standalone
  datasource:
    url: jdbc:h2:file:./h2data/jegykassza-application
    driver-class-name: org.h2.Driver
    username: jegykassza
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect